### ISSUE TITLE
The user-provided path public does not exist

### ISSUE THREAD

**Issue by Ugarz** [jakejarvis/s3-sync-action#19]
Hello,

I'm interested in this action to deploy my website auto-magically when I push on master. Quite simple case I think, following both the Github Actions guide and the Readme of this action I managed to trigger the workflow and setup my secrets.

My issue : every time I'm trying to push on the `master` branch my action is triggered but crash at the deploy step because `The user-provided path public does not exist`.
I searched some similar cases but could not find informations on it and I'm not quite sure if this is a Github secrets / AWS rights issue.
I think it's coming from my Github secrets `AWS_S3_BUCKET`, but in the documentation it says

> The name of the bucket you're syncing to. For example, `jarv.is` or `my-app-releases`.

My bucket is something like `awesomewebsite.fr` so I've put this in Github secrets with `AWS_S3_BUCKET`.

Any advice ?

**Comment by muhammetgokturkayan** [comment]
Hello,

It's looking for "public" folder. Just remove this line.
     SOURCE_DIR: 'public'      # optional: defaults to entire repository

Source_DIR is a nice feature but removing it from example might be nice. It tricked me too.

**Comment by ChristopherAUGSCM** [comment]
Have you added - uses: actions/checkout@master ?

This ensures that actions can gain access to whichever repository branch that you're trying to use.

This is what fixed the bug for me

**Comment by Nostrathomas0** [comment]
I've given this a try. Since I'm trying to upload a whole directory for a static website I'm using the --recursive flat on the s3 sync. That error seems to override the "user-given path not found error" because when I use that flag the error says it's an unknown option. I don't know if it's a problem with the local path. I can't imagine why it would throw errors, I've tried all sorts of options for local path.
